### ISSUE TITLE
安装完成 hexo-filter-github-emojis 后执行 hexo clean报错

### ISSUE THREAD

**Issue by Doslin** [crimx/hexo-filter-github-emojis#16]
## hexo-filter-github-emojis为今天下载的版本，错误如下：
/usr/local/hexo/node_modules/hexo-filter-github-emojis/index.js:21
  )
  ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at fs.readFile.then.script (/usr/local/hexo/node_modules/hexo/lib/hexo/index.js:238:19)
    at tryCatcher (/usr/local/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/hexo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/hexo/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/usr/local/hexo/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/local/hexo/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/usr/local/hexo/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/usr/local/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/hexo/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/usr/local/hexo/node_modules/bluebird/js/release/promise.js:638:18)
    at /usr/local/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /usr/local/hexo/node_modules/graceful-fs/graceful-fs.js:90:16
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
INFO  Deleted database.

**Comment by crimx** [comment]
你的 Node 版本是不是过低？

**Comment by Doslin** [comment]
## 原因：NodeJS版本过低
#### 问题得到解决
@crimx  谢谢~
